volumes:
  open-webui:

networks:
  ai_server_net:
    external: true

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    volumes:
      - open-webui:/app/backend/data
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - ai_server_net

secrets:
  tsauthkey:
    file: ~/.config/tsauthkey