volumes:
  n8n_storage:

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    env_file:
      - ".env"
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./local_files:/files
    networks:
      - ai_server_net

networks:
  ai_server_net:
    external: true
