services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - ai_server_net

networks:
  ai_server_net:
    external: true
