volumes:
  ollama_storage:

networks:
  ai_server_net:
    external: true

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ollama_storage:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - ai_server_net
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
